VMS=kvm.centos6  kvm.host-vbox  kvm.host-vz  kvm.kemukins  vz.kemukins

all:

kvm.centos6:
	(cd $@ && make)

kvm.host-vbox:
	(cd $@ && make)

kvm.host-vz:
	(cd $@ && make)

kvm.kemukins:
	(cd $@ && make)

vz.kemukins:
	(cd $@ && make)

.PHONY: $(VMS)
